
# nome do WorkFlow
name: GitHub Demo 2
run-name: ${{ github.actor }} is learning GitHub Actions

# disparador ou trigger
on:
  workflow_dispatch:
    


jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
